apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 086457974500.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 086457974500.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: a6612ecd
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
